### PR TITLE
landing page with responsiveness

### PR DESCRIPTION
**Pull request by KoushikKintali**
Landing Page for NaN-UI

You can refer to the page in https://nan-ui.netlify.app/

image

### CODE REVIEW

**Review by vijaytembugade — APPROVED** [review]
Looks amazing!

**Review by MiheerTamkhane — APPROVED** [review]
Looks nice.

**Review by manojasarsa — APPROVED** [review]
Looks clean! Good to go :)

**Review by mimansha-swarup — APPROVED** [review]
good to go 👍

**Review by horsemaker — COMMENTED** [review]
looks pretty clean!

**Review by MarkVed17 — APPROVED** [review]
Such a clean UI. Also, I like the library name. So far, so good.

**Pull request merged**
